---
development:
  cloud_name: snake
  api_key: '123788616947241'
  api_secret: 10mmD-mjRGnvhtJuBi2cjFrOMPc
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: snake
  api_key: '123788616947241'
  api_secret: 10mmD-mjRGnvhtJuBi2cjFrOMPc
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: snake
  api_key: '123788616947241'
  api_secret: 10mmD-mjRGnvhtJuBi2cjFrOMPc
  enhance_image_tag: true
  static_image_support: false
